# Practice on Numpy and Pandas

Here are some task for you, to refresh what you saw in the notebooks before.

It will help you strengthen the **learning objectives** from the notebook before. You should be able to
- create numpy arrays
- manipulate them with basic mathematics operators
- extract rows, columns and items by indexing
- use aggregation methods (like sum, min, max, std) on numpy arrays


**Part 1**: Creating numpy arrays.

- Please create a numpy array from the list:
```Python
my_list = [1, 2, 5, 6, 8]
````

- Please create a numpy array containing the values from 1 to 10.
- Please create a numpy array from 0 to 5 cwith a stepsize of 0.2
- Create a numpy array with the shape 2,3 with random values

In [1]:
import numpy as np

In [2]:
# 1. Please create a numpy array from the list.
my_list = [1, 2, 5, 6, 8]
my_array = np.array(my_list)
my_array

array([1, 2, 5, 6, 8])

In [3]:
# 2. Please create a numpy array containing the values from 1 to 10.
range_arr = np.arange(1,11)
range_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# 3. Please create a numpy array from 0 to 5 cwith a stepsize of 0.2
range_arr_2 = np.arange(0, 5.2, 0.2)
range_arr_2

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ])

In [5]:
# 4. Create a numpy array with the shape 2,3 with random values
random_arr = np.random.rand(2, 3)
random_arr

array([[0.33693024, 0.54840171, 0.9916301 ],
       [0.88899893, 0.33158556, 0.78263085]])

**Part 2**: Manipulate numpy arrays.

1. Please create a numpy array with (1, 3, '4', 7, 12, '0'). Define the content as integer.
2. Check the data type of the objects and the shape of the array
3. Update the 4th value to 30.
4. Reshape the array to a 2x3 matrix.
5. Please add 8 to each value in the the first row and 12 to each in the second row.
6. Mulitply the first column with 2, the second with 3 and the third with 4.
7. Please summ up all numbers in the first row, and all numbers in the second row.
8. Similarly, search for the largest number for each column.
9. Extract the number in the second column and the first row.
10. Check at which index the value is exactly 48.

In [6]:
# 1. Please create a numpy array with (1, 3, '4', 7, 12, '0'). Define the content as integer.
my_array = np.array([1, 3, '4', 7, 12, '0'], np.int32) 

In [7]:
# 2. Check the data type of the objects and the shape of the array
print('Data type: ', my_array.dtype)
print('Shape: ', my_array.shape)

Data type:  int32
Shape:  (6,)


In [8]:
# 3. Update the 4th value to 30.
my_array[3] = 30
my_array

array([ 1,  3,  4, 30, 12,  0], dtype=int32)

In [9]:
# 4. Reshape the array to a 2x3 matrix.
my_array = my_array.reshape(2, 3)
my_array

array([[ 1,  3,  4],
       [30, 12,  0]], dtype=int32)

In [10]:
# 5. Please add 8 to the first row and 12 to the second row.
my_array = my_array + [[8], [12]]
my_array

array([[ 9, 11, 12],
       [42, 24, 12]])

In [11]:
# 6. Mulitply the first column with 2, the second with 3 and the third with 4.
my_array = my_array * [2, 3, 4]
my_array

array([[18, 33, 48],
       [84, 72, 48]])

In [12]:
# 7. Please summ up all numbers in the first row, and all numbers in the second row.
my_array.sum(axis=1)

array([ 99, 204])

In [13]:
# 8. Similarly, search for the largest number for each column.
my_array.max(axis=0)

array([84, 72, 48])

In [14]:
# 9. Extract the number in the second column and the first row.
my_array[0, 1]

33

In [15]:
my_array

array([[18, 33, 48],
       [84, 72, 48]])

In [16]:
# 10. Check at which index the value is exactly 48.
np.where(my_array == 48)

(array([0, 1]), array([2, 2]))