# Practice on NumPy and pandas

Here are some task for you, to refresh what you saw in the notebooks before.

It will help you strengthen the **learning objectives** from the notebook before. You should be able to
- create NumPy arrays
- manipulate them with basic mathematics operators
- extract rows, columns and items by indexing
- use aggregation methods (like sum, min, max, std) on NumPy arrays


## Part 1: Creating NumPy arrays.

1. Please create a NumPy array from the list:
```Python
my_list = [1, 2, 5, 6, 8]
````

- Please create a numpy array containing the values from 1 to 10.
-  Please create a numpy array from 0 to 5 with a step size of 0.2
- Create a numpy array with the shape 2,3 with random values


In [1]:
import numpy as np

2. Please create a NumPy array containing the values from 1 to 10.


In [2]:
# 1. Create a NumPy array from the list
my_list = [1, 2, 5, 6, 8]
arr_from_list = np.array(my_list)
print("Array from list:", arr_from_list)

Array from list: [1 2 5 6 8]


In [3]:
# 2. Create a numpy array containing values from 1 to 10
arr_1_to_10 = np.arange(1, 11)
print("1 to 10:", arr_1_to_10)

1 to 10: [ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# 3. Create a numpy array from 0 to 5 with step size 0.2
arr_step = np.arange(0, 5.2, 0.2)
print("0 to 5 step 0.2:", arr_step)
# 4. Create a 2x3 array with random values
arr_random = np.random.rand(2, 3)
print("Random 2x3 array:\n", arr_random)

0 to 5 step 0.2: [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5. ]
Random 2x3 array:
 [[0.84104163 0.23922309 0.23307957]
 [0.88327828 0.66977291 0.02098378]]


3. Please create a NumPy array from 0 to 5 with a step size of 0.2


In [5]:
# 3. Create a numpy array from 0 to 5 with step size 0.2
arr_step = np.arange(0, 5.2, 0.2)
print("0 to 5 step 0.2:", arr_step)

0 to 5 step 0.2: [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5. ]


# Practice on NumPy and pandas

Here are some task for you, to refresh what you saw in the notebooks before.

It will help you strengthen the **learning objectives** from the notebook before. You should be able to
- create NumPy arrays
- manipulate them with basic mathematics operators
- extract rows, columns and items by indexing
- use aggregation methods (like sum, min, max, std) on NumPy arrays


## Part 1: Creating NumPy arrays.

1. Please create a NumPy array from the list:
```Python
my_list = [1, 2, 5, 6, 8]
````

- Please create a numpy array containing the values from 1 to 10.
-  Please create a numpy array from 0 to 5 with a step size of 0.2
- Create a numpy array with the shape 2,3 with random values


In [6]:
import numpy as np

2. Please create a NumPy array containing the values from 1 to 10.


In [7]:
# 1. Create a NumPy array from the list
my_list = [1, 2, 5, 6, 8]
arr_from_list = np.array(my_list)
print("Array from list:", arr_from_list)

Array from list: [1 2 5 6 8]


3. Please create a NumPy array from 0 to 5 with a step size of 0.2
arr_step = np.arange(0, 5 + 0.2, 0.2)
print(arr_step)

In [8]:
arr_step = np.arange(0, 5 + 0.2, 0.2)
print(arr_step)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5. ]


4. Create a NumPy array with the shape 2,3 with random values


In [9]:
import numpy as np

arr_random = np.random.rand(2, 3)
print(arr_random)

[[0.64238993 0.71841749 0.49376453]
 [0.162387   0.26274978 0.5894439 ]]


## Part 2: Manipulate NumPy arrays.

1. Please create a NumPy array with (1, 3, '4', 7, 12, '0'). Define the content as integer.


In [10]:
import numpy as np

arr = np.array([1, 3, '4', 7, 12, '0'], dtype=int)
print(arr)
print(arr.dtype)

[ 1  3  4  7 12  0]
int64


2. Check the data type of the objects and the shape of the array


In [11]:
import numpy as np

arr = np.array([1, 3, '4', 7, 12, '0'], dtype=int)

# Check data type
print("Data type:", arr.dtype)

# Check shape
print("Shape:", arr.shape)

Data type: int64
Shape: (6,)


3. Update the 4th value to 30.


In [12]:
import numpy as np

arr = np.array([1, 3, '4', 7, 12, '0'], dtype=int)

# Update the 4th value (index 3) to 30
arr[3] = 30

arr

array([ 1,  3,  4, 30, 12,  0])

4. Reshape the array to a 2x3 matrix.


In [13]:
import numpy as np

arr = np.array([1, 3, '4', 7, 12, '0'], dtype=int)

# update 4th value
arr[3] = 30

# reshape to 2x3
arr_reshaped = arr.reshape(2, 3)

arr_reshaped

array([[ 1,  3,  4],
       [30, 12,  0]])

5. Please add 8 to each value in the first row and 12 to each in the second row.


In [14]:
# Starting from the reshaped array
arr = np.array([1, 3, 4, 30, 12, 0], dtype=int).reshape(2, 3)

# Add 8 to first row, 12 to second row
arr_modified = arr + np.array([[8, 8, 8],
                               [12, 12, 12]])

arr_modified

array([[ 9, 11, 12],
       [42, 24, 12]])

6. Multiply the first column with 2, the second with 3 and the third with 4.


In [15]:
arr = np.array([[ 9, 11, 12],
                [42, 24, 12]])

# Multiply columns: col1*2, col2*3, col3*4
arr_scaled = arr * np.array([2, 3, 4])

arr_scaled

array([[18, 33, 48],
       [84, 72, 48]])

7. Please sum up all numbers in the first row, and all numbers in the second row.


In [16]:
import numpy as np

arr = np.array([[ 9, 11, 12],
                [42, 24, 12]])

row_sums = arr.sum(axis=1)
row_sums

array([32, 78])

8. Similarly, search for the largest number for each column.
import numpy as np

arr = np.array([[ 9, 11, 12],
                [42, 24, 12]])

col_max = arr.max(axis=0)
col_max

In [17]:
import numpy as np

arr = np.array([[ 9, 11, 12],
                [42, 24, 12]])

col_max = arr.max(axis=0)
col_max

array([42, 24, 12])

9. Extract the number in the second column and the first row.


In [18]:
value = arr[0, 1]
value

np.int64(11)

10. Check at which index the value is exactly 48.

In [19]:
import numpy as np

index_48 = np.where(arr == 48)
index_48

(array([], dtype=int64), array([], dtype=int64))

4. Create a NumPy array with the shape 2,3 with random values


In [20]:
import numpy as np

arr = np.random.rand(2, 3)   # values between 0 and 1
arr

array([[0.60881848, 0.65816351, 0.10947461],
       [0.21026189, 0.29047961, 0.76919421]])

## Part 2: Manipulate NumPy arrays.

1. Please create a NumPy array with (1, 3, '4', 7, 12, '0'). Define the content as integer.


In [21]:
import numpy as np

# 1. Create a NumPy array with (1, 3, '4', 7, 12, '0') as integers
arr = np.array([1, 3, '4', 7, 12, '0'], dtype=int)
print("1) Initial array:", arr)

1) Initial array: [ 1  3  4  7 12  0]


2. Check the data type of the objects and the shape of the array


In [22]:
print("2) Data type:", arr.dtype)
print("   Shape:", arr.shape)

2) Data type: int64
   Shape: (6,)


3. Update the 4th value to 30.


In [23]:
arr[3] = 30
print("3) After updating 4th value to 30:", arr)

3) After updating 4th value to 30: [ 1  3  4 30 12  0]


4. Reshape the array to a 2x3 matrix.


In [24]:
arr2 = arr.reshape(2, 3)
print("4) Reshaped to 2x3:\n", arr2)

4) Reshaped to 2x3:
 [[ 1  3  4]
 [30 12  0]]


5. Please add 8 to each value in the first row and 12 to each in the second row.


In [25]:
arr5 = arr2.copy()
arr5[0] += 8
arr5[1] += 12
print("5) After adding 8 to row 1, 12 to row 2:\n", arr5)

5) After adding 8 to row 1, 12 to row 2:
 [[ 9 11 12]
 [42 24 12]]


6. Multiply the first column with 2, the second with 3 and the third with 4.


In [26]:
multipliers = np.array([2, 3, 4])
arr6 = arr5 * multipliers
print("6) After column-wise multiplication (2,3,4):\n", arr6)

6) After column-wise multiplication (2,3,4):
 [[18 33 48]
 [84 72 48]]


7. Please sum up all numbers in the first row, and all numbers in the second row.


In [27]:
row_sums = arr6.sum(axis=1)
print("7) Row sums:", row_sums)

7) Row sums: [ 99 204]


8. Similarly, search for the largest number for each column.


In [28]:
col_max = arr6.max(axis=0)
print("8) Max per column:", col_max)

8) Max per column: [84 72 48]


9. Extract the number in the second column and the first row.


In [29]:
value_2ndcol_1strow = arr6[0, 1]
print("9) Value at (row 0, col 1):", value_2ndcol_1strow)

9) Value at (row 0, col 1): 33


10. Check at which index the value is exactly 48.

In [30]:
indices_48 = np.where(arr6 == 48)
print("10) Indices where value == 48:", indices_48)
# If you want them as (row, col) pairs:
print("    As (row, col) list:", list(zip(indices_48[0], indices_48[1])))

10) Indices where value == 48: (array([0, 1]), array([2, 2]))
    As (row, col) list: [(np.int64(0), np.int64(2)), (np.int64(1), np.int64(2))]
